a = (input("Digite um número: "))
print(a.isnumeric())
print(a.isalnum())
print(a.isalpha())
print(a.isascii())
print(a.isdecimal())
print(a.isdigit())
print(a.isidentifier())
print(a.isdigit())
print(a.islower())
print(a.isprintable())
print(a.isspace())
print(a.istitle())